pipeline:
    compile:
        image: microsoft/aspnetcore-build
        commands:
            - sh build.sh
    build-image:
        command:
            - docker build -t dotnetcore-container ./Web
              docker tag dotnetcore-container xiar/dotnetcore-container
              docker push xiar/dotnetcore-container
